-- =========================================================
-- CREATE TONGHOPKCB TABLES (tonghopkcb -> tonghopkcb15)
-- =========================================================
-- 16 tables với cấu trúc giống hệt nhau
-- =========================================================

-- Table 1: tonghopkcb
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 2: tonghopkcb1
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb1 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 3: tonghopkcb2
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb2 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 4: tonghopkcb3
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb3 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 5: tonghopkcb4
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb4 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 6: tonghopkcb5
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb5 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 7: tonghopkcb6
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb6 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 8: tonghopkcb7
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb7 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 9: tonghopkcb8
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb8 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 10: tonghopkcb9
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb9 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 11: tonghopkcb10
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb10 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 12: tonghopkcb11
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb11 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 13: tonghopkcb12
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb12 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 14: tonghopkcb13
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb13 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 15: tonghopkcb14
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb14 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- Table 16: tonghopkcb15
CREATE TABLE IF NOT EXISTS iceberg.v4.tonghopkcb15 (
    Id UUID NOT NULL,
    TenantId UUID,
    ma_lk VARCHAR,
    stt BIGINT,
    ma_bn VARCHAR,
    ho_ten VARCHAR,
    so_cccd VARCHAR,
    ngay_sinh TIMESTAMP,
    gioi_tinh INTEGER,
    nhom_mau VARCHAR,
    ma_quoctich VARCHAR,
    ma_dantoc VARCHAR,
    ma_nghe_nghiep VARCHAR,
    dia_chi VARCHAR,
    matinh_cu_tru VARCHAR,
    mahuyen_cu_tru VARCHAR,
    maxa_cu_tru VARCHAR,
    dien_thoai VARCHAR,
    ma_the_bhyt VARCHAR,
    ma_dkbd VARCHAR,
    gt_the_tu VARCHAR,
    gt_the_den VARCHAR,
    ngay_mien_cct TIMESTAMP,
    ly_do_vv VARCHAR,
    ly_do_vnt VARCHAR,
    ma_ly_do_vnt VARCHAR,
    chan_doan_vao VARCHAR,
    chan_doan_rv VARCHAR,
    ma_benh_chinh VARCHAR,
    ma_benh_kt VARCHAR,
    ma_benh_yhct VARCHAR,
    ma_pttt_qt VARCHAR,
    ngay_tai_kham VARCHAR,
    ma_hsba VARCHAR,
    ma_ttdv VARCHAR,
    du_phong VARCHAR,
    ApiRequestId UUID
)
WITH (format = 'PARQUET');

-- =========================================================
-- VERIFY ALL TABLES
-- =========================================================
SHOW TABLES IN iceberg.v4;

-- Verify specific tables
DESCRIBE iceberg.v4.tonghopkcb;
DESCRIBE iceberg.v4.tonghopkcb15;

-- =========================================================
-- OPTIONAL: DROP ALL TABLES
-- =========================================================
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb1;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb2;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb3;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb4;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb5;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb6;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb7;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb8;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb9;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb10;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb11;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb12;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb13;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb14;
-- DROP TABLE IF EXISTS iceberg.v4.tonghopkcb15;
